openapi: 3.0.0
info:
  title: "KEV API"
  description: "An API made by KEV"
  version: "1.0.0"

servers:
  [url: "/api"]

components:
  schemas:
    Devices:
      type: "object"
      required: ["id"]
      properties:
        id:
          type: "string"
        name:
          type: "string"
        txPower:
          type: "integer"
        


paths:
  /device:
    get:
      operationId: "device.read"
      tags: ["Device"]
      summary: "Read the list of devices"
      responses:
        "200":
          description: "Successfully read devices list"
    post:
      operationId: "device.create"
      tags: ["Device"]
      summary: "Create a new device"
      requestBody:
        description: "Device to create"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "device"
              $ref: "#/components/schemas/Devices"
      responses:
        "201":
          description: "Successfully created a new Device"
